version: 0.2
  
phases:  
  install:
      commands:
    pre_build:
      commands:
    build:
      commands:
    post_build:
      commands:
artifacts:
  files: 
    - '**/*'
  base-directory: 'my-build*'
  discard-paths: yes
